# Generated by Django 3.1.5 on 2021-11-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='id',
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id_prop',
            field=models.CharField(default='1', max_length=20000, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
