# Generated by Django 3.1.5 on 2021-11-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=25, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=25, verbose_name='Longitude'),
        ),
    ]
