# Generated by Django 3.1.5 on 2021-11-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211123_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=25, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='longitude',
            field=models.DecimalField(decimal_places=14, max_digits=25, verbose_name='Longitude'),
        ),
    ]
