# Generated by Django 3.1.5 on 2021-11-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211123_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=25, verbose_name='Latitude'),
        ),
    ]
